name       : polychromatic
version    : 0.3.12
release    : 10
source     :
    - https://github.com/polychromatic/polychromatic/archive/v0.3.12.tar.gz : 1ee4e64f713851e62100931f2f76c9cfd73b44aa7eefbcd4e2fad92cc9a1c638
license    : GPL-3.0-or-later
component  : system.utils
networking : yes
summary    : Graphical front end and tray applet for configuring Razer peripherals
    on GNU/Linux
description: |
    A front-end for customising the functionality of your Razer perpherials under GNU/Linux.
builddeps  :
    - nodejs
rundeps    :
    - python-setproctitle
    - python-requests
    - python3-gobject
    - imagemagick
    - libwebkit-gtk
    - libappindicator
    - openrazer
build      : |
    npm install less
install    : |
    %make_install LESSC=node_modules/less/bin/lessc
