name       : polychromatic
version    : 0.7.0
release    : 20
source     :
    - https://github.com/polychromatic/polychromatic/archive/refs/tags/v0.7.0.tar.gz : 0672ac49d4f4961e5d822c2310530a63d7ed61add0986f23c4931c4c2dc98fca
license    : GPL-3.0-or-later
component  : system.utils
networking : yes
summary    : Graphical front end and tray applet for configuring Razer peripherals
description: |
    A front-end for customising the functionality of your Razer perpherials.
builddeps  :
    - sassc
rundeps    :
    - imagemagick
    - libayatana-appindicator
    - openrazer-current
    - python-colorama
    - python-colour
    - python-gobject
    - python-setproctitle
    - python-qtwebengine
    - python-requests
    - python3-qt5
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-AyatanaAppIndicator.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
